2025-06-15 18:42:18.061 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2025-06-15 18:42:18.263 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=9 from 2025-06-11 21:29:43.376009)
2025-06-16 02:29:03.692 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-06-16 02:29:09.460 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_3] is still running at shutdown: File "/usr/local/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1045, in _bootstrap_inner
    self._delete()
  File "/usr/local/lib/python3.13/threading.py", line 996, in run
    del self._target, self._args, self._kwargs
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 110, in _worker
    return
